---
distributions:
  sandbox-infra-test:
    id: "E12AN388E0D4UU"
    prefix: "/infra-test-only"
  test-1:
    id: "E12AN388E0D4UU"
    prefix: "/infra-test-only/test-1"
  test-2:
    id: "ABCD1234"
    prefix: "/infra-test-only/test-2"
entitlements:
  10gen-devops-core:
    - sandbox-infra-test
    - test-1
    - test-2
